### ISSUE TITLE
Not available on Maven

### ISSUE THREAD

**Issue by Michael-Kyriacou** [xSAVIKx/openweathermap-java-api#2]
Hi, is there a maven dependency I can add to my maven Java project to get this code? If not, is there a different way that I can use the existing donwloaded zip file in my maven project?

Thank you.

**Comment by xSAVIKx** [comment]
@Michael-Kyriacou Hi. It is available as a Maven dependency with Bintray repository. Take a look at the [projects page](https://bintray.com/xsavikx/openweathermap-java-api/api-core/1.0). There is a `set me up!` button which you can use in order to setup your Maven configuration.

The other way — you can clone the repository, run `gradlew clean build install` and configure your maven to look for dependencies within the local repository.
